version: "3.7"
services:
    # image project
    laravel_7:
        build:
            args:
                user: teste
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: especializati/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - laravel-eti

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-eti

    # db mysql
    mysql:
        image: mariadb:10.5.8
        restart: unless-stopped
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - laravel-eti

    # queue
    queue:
        build:
            args:
                user: teste
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-eti

networks:
    laravel-eti:
        driver: bridge
